// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package word

import (
	"proxima-vocabulary/app/gateway/api/word"
	v1 "proxima-vocabulary/app/word/api/words/v1"
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"proxima-vocabulary/app/gateway/utility"
)

type ControllerV1 struct{
	WordsClient v1.WordsClient
}

func NewV1() word.IWordV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("word", grpcx.Client.ChainUnary(
		utility.GrpcClientTimeout,
	))
  
    return &ControllerV1{  
       WordsClient: v1.NewWordsClient(conn),  
    }
}
