version: "3.7"

services:
  etcd:
    image: "bitnami/etcd:3.5"
    container_name: "etcd"
    restart: "always"
    ports:
      - 12379:2379
    environment:
      - TZ=Europe/London
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379